import { chromium, expect } from '@playwright/test';
import { createServer } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import { readFile, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const fixture=JSON.parse(await readFile(process.env.MEMBERS_FIXTURE_FILE,'utf8'));
const backend=new URL(process.env.MEMBERS_BACKEND_URL);
assert.equal(backend.hostname,'127.0.0.1');
const output=process.env.MEMBERS_EVIDENCE_OUTPUT;
let localOrigin;
const server=await createServer({configFile:false,root:process.cwd(),logLevel:'silent',plugins:[react()],resolve:{alias:{'@':fileURLToPath(new URL('../../src',import.meta.url))}},server:{host:'127.0.0.1',port:0,proxy:{'/api':{target:backend.origin,changeOrigin:true,configure(proxy){proxy.on('proxyReq',(proxyReq,request)=>{if(localOrigin && request.headers.origin===localOrigin)proxyReq.setHeader('Origin','http://localhost:5173');});}}}}});
let browser;
const responses=[],errors=[];
try {
 // Only this isolated loopback origin is translated; the backend CORS policy stays unchanged.
 await server.listen();const baseURL=`http://127.0.0.1:${server.httpServer.address().port}`;localOrigin=baseURL;
 browser=await chromium.launch();const context=await browser.newContext({baseURL,viewport:{width:1440,height:1000}});
 await context.route('**/*',r=>new URL(r.request().url()).origin===baseURL?r.continue():r.abort());
 const page=await context.newPage();page.on('pageerror',e=>errors.push(e.name));
 page.on('response',r=>{const p=new URL(r.url()).pathname;if(p.startsWith('/api/company-chef/members')) responses.push({method:r.request().method(),path:p,status:r.status()});});
 await page.goto('/login');await page.getByLabel('이메일',{exact:true}).fill(fixture.email);await page.getByLabel('비밀번호',{exact:true}).fill(fixture.password);
 await page.getByRole('button',{name:'로그인',exact:true}).click();await expect(page).toHaveURL(/company\/dashboard/);
 await page.goto('/company/user-management');await expect(page.getByText('검색 결과 2명')).toBeVisible();
 await page.getByRole('button',{name:'사용자 등록',exact:true}).click();
 const dialog=page.getByRole('dialog');await dialog.getByLabel('이름 *',{exact:true}).fill('브라우저 등록');
 await dialog.getByLabel('연락처 *').fill('01012345678');await dialog.getByLabel('이메일 *').fill('member-browser-created@example.test');
 await dialog.getByLabel('비밀번호 *',{exact:true}).fill(fixture.password);await dialog.getByLabel('비밀번호 확인 *').fill(fixture.password);
 await dialog.getByRole('button',{name:'등록',exact:true}).click();await expect(dialog).toBeHidden();
 await expect(page.getByText('검색 결과 3명')).toBeVisible();
 await page.getByLabel('사용자 이름 검색').fill('브라우저');await page.getByRole('button',{name:'검색',exact:true}).click();
 await expect(page.getByText('검색 결과 1명')).toBeVisible();
 await page.getByRole('button',{name:'브라우저 등록 수정'}).click();await dialog.getByLabel('이름 *',{exact:true}).fill('브라우저 수정');
 await dialog.getByRole('button',{name:'수정',exact:true}).click();await expect(dialog).toBeHidden();await expect(page.getByRole('cell',{name:'브라우저 수정',exact:true})).toBeVisible();
 await page.screenshot({path:path.join(output,'desktop.png'),fullPage:true,animations:'disabled',mask:[page.getByRole('button',{name:'계정 메뉴'})]});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'브라우저 수정 수정'}).click();
 await expect(dialog.getByRole('button',{name:'수정',exact:true})).toBeInViewport();
 await expect(page.locator('.MuiDialog-container')).toHaveCSS('opacity','1');
 await page.screenshot({path:path.join(output,'mobile-dialog.png'),animations:'disabled',mask:[page.getByRole('button',{name:'계정 메뉴'})]});
 await page.keyboard.press('Escape');await expect(dialog).toBeHidden();
 await page.screenshot({path:path.join(output,'mobile-list.png'),animations:'disabled',mask:[page.getByRole('button',{name:'계정 메뉴'})]});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.getByRole('button',{name:'브라우저 수정 삭제'}).click();await dialog.getByRole('button',{name:'삭제',exact:true}).click();
 await expect(dialog).toBeHidden();await expect(page.getByText('검색 결과가 없습니다.')).toBeVisible();
 assert.deepEqual(errors,[]);assert.equal(responses.some(r=>r.status>=500),false);
 assert.equal(responses.some(r=>r.method==='POST'&&r.status===201),true);
 assert.equal(responses.some(r=>r.method==='PUT'&&r.status===200),true);
 assert.equal(responses.some(r=>r.method==='DELETE'&&r.status===204),true);
 await writeFile(path.join(output,'result.json'),JSON.stringify({passed:true,environment:'isolated local synthetic MySQL and real member APIs',responses,pageErrors:errors},null,2));
} finally {await browser?.close();await server.close();}
